commented;modifiers;parameterAmount;loc;comment;code
false;public;0;13;;@Test public void testAsyncEndpoint() throws Exception {     getMockEndpoint("mock:before").expectedBodiesReceived("Hello Camel").     getMockEndpoint("mock:after").expectedBodiesReceived("MyFailureHandler").     getMockEndpoint("mock:result").expectedBodiesReceived("MyFailureHandler").     String reply = template.requestBody("direct:start", "Hello Camel", String.class).     assertEquals("Bye Camel", reply).     assertMockEndpointsSatisfied().     assertFalse("Should use different threads", beforeThreadName.equalsIgnoreCase(afterThreadName)). }
false;public;1;3;;public void process(Exchange exchange) throws Exception {     afterThreadName = Thread.currentThread().getName(). }
false;public;1;3;;public void process(Exchange exchange) throws Exception {     beforeThreadName = Thread.currentThread().getName(). }
false;public;0;27;;@Override public void configure() throws Exception {     context.addComponent("async", new MyAsyncComponent()).     // the onException can be asynchronous as well so we have to test for that     onException(IllegalArgumentException.class).continued(true).to("mock:before").to("log:before").process(new Processor() {          public void process(Exchange exchange) throws Exception {             beforeThreadName = Thread.currentThread().getName().         }     }).to("async:MyFailureHandler").process(new Processor() {          public void process(Exchange exchange) throws Exception {             afterThreadName = Thread.currentThread().getName().         }     }).to("log:after").to("mock:after").     from("direct:start").throwException(new IllegalArgumentException("Damn")).to("mock:result").transform(constant("Bye Camel")). }
false;protected;0;32;;@Override protected RouteBuilder createRouteBuilder() throws Exception {     return new RouteBuilder() {          @Override         public void configure() throws Exception {             context.addComponent("async", new MyAsyncComponent()).             // the onException can be asynchronous as well so we have to test for that             onException(IllegalArgumentException.class).continued(true).to("mock:before").to("log:before").process(new Processor() {                  public void process(Exchange exchange) throws Exception {                     beforeThreadName = Thread.currentThread().getName().                 }             }).to("async:MyFailureHandler").process(new Processor() {                  public void process(Exchange exchange) throws Exception {                     afterThreadName = Thread.currentThread().getName().                 }             }).to("log:after").to("mock:after").             from("direct:start").throwException(new IllegalArgumentException("Damn")).to("mock:result").transform(constant("Bye Camel")).         }     }. }
