# id;timestamp;commentText;codeText;commentWords;codeWords
ResponseException -> public Response getResponse();1524684173;Returns the {@link Response} that caused this exception to be thrown.;public Response getResponse() {_        return response__    };returns,the,link,response,that,caused,this,exception,to,be,thrown;public,response,get,response,return,response
ResponseException -> public Response getResponse();1538170812;Returns the {@link Response} that caused this exception to be thrown.;public Response getResponse() {_        return response__    };returns,the,link,response,that,caused,this,exception,to,be,thrown;public,response,get,response,return,response
ResponseException -> public Response getResponse();1548869519;Returns the {@link Response} that caused this exception to be thrown.;public Response getResponse() {_        return response__    };returns,the,link,response,that,caused,this,exception,to,be,thrown;public,response,get,response,return,response
ResponseException -> public Response getResponse();1549439027;Returns the {@link Response} that caused this exception to be thrown.;public Response getResponse() {_        return response__    };returns,the,link,response,that,caused,this,exception,to,be,thrown;public,response,get,response,return,response
ResponseException -> ResponseException(ResponseException e) throws IOException;1524684173;Wrap a {@linkplain ResponseException} with another one with the current_stack trace. This is used during synchronous calls so that the caller_ends up in the stack trace of the exception thrown.;ResponseException(ResponseException e) throws IOException {_        super(e.getMessage(), e)__        this.response = e.getResponse()__    };wrap,a,linkplain,response,exception,with,another,one,with,the,current,stack,trace,this,is,used,during,synchronous,calls,so,that,the,caller,ends,up,in,the,stack,trace,of,the,exception,thrown;response,exception,response,exception,e,throws,ioexception,super,e,get,message,e,this,response,e,get,response
ResponseException -> ResponseException(ResponseException e) throws IOException;1538170812;Wrap a {@linkplain ResponseException} with another one with the current_stack trace. This is used during synchronous calls so that the caller_ends up in the stack trace of the exception thrown.;ResponseException(ResponseException e) throws IOException {_        super(e.getMessage(), e)__        this.response = e.getResponse()__    };wrap,a,linkplain,response,exception,with,another,one,with,the,current,stack,trace,this,is,used,during,synchronous,calls,so,that,the,caller,ends,up,in,the,stack,trace,of,the,exception,thrown;response,exception,response,exception,e,throws,ioexception,super,e,get,message,e,this,response,e,get,response
ResponseException -> ResponseException(ResponseException e) throws IOException;1548869519;Wrap a {@linkplain ResponseException} with another one with the current_stack trace. This is used during synchronous calls so that the caller_ends up in the stack trace of the exception thrown.;ResponseException(ResponseException e) throws IOException {_        super(e.getMessage(), e)__        this.response = e.getResponse()__    };wrap,a,linkplain,response,exception,with,another,one,with,the,current,stack,trace,this,is,used,during,synchronous,calls,so,that,the,caller,ends,up,in,the,stack,trace,of,the,exception,thrown;response,exception,response,exception,e,throws,ioexception,super,e,get,message,e,this,response,e,get,response
